version: "3.8"

services:
  asdf_service:
    container_name: asdf_service_container
    image: asdf:latest
    ports:
      - 9000:8000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000"]
      interval: 30s
      timeout: 15s
      retries: 5
    # this is a production command
    command:
      [
        "gunicorn",
        "asdf.main:app",
        "--bind=:8000",
        "--workers=1",
        "--threads=8",
        "--timeout=0",
        "--worker-class=uvicorn.workers.UvicornWorker",
      ]
